### ISSUE TITLE
Q: Is it Possible to use fakechroot/fakeroot-ng with Golang Binaries

### ISSUE THREAD

**Issue by munagekar** [dex4er/fakechroot#83]
Golang uses syscalls directly and does not use glibc. 

I was trying to get [syncthing](https://github.com/syncthing/syncthing) to work inside a fakechroot. However it fails with /usr/bin/syncthing not in path. It is in path, however since it uses syscalls directly, it does not work. This error is similar to https://github.com/dex4er/fakechroot/issues/67. 

Is it possible to use [fakeroot-ng](https://fakeroot-ng.lingnu.com/index.php?title=Main_Page) with fakechroot ? I checked the documentation for fakechroot but couldn't find the use of fakeroot-ng ?

**Comment by munagekar** [comment]
<details><summary>Stack trace with Syncthing</summary>
<p>

```
root@abi-0:/# syncthing
[monitor] 06:56:57 INFO: Default folder created and/or linked to new config
[monitor] 06:56:57 WARNING: Error starting the main Syncthing process: exec: "syncthing": executable file not found in $PATH
panic: Error starting the main Syncthing process

goroutine 1 [running]:
main.monitorMain(0xc000156930, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/syncthing/syncthing/cmd/syncthing/monitor.go:125 +0x14f3
main.main()
        github.com/syncthing/syncthing/cmd/syncthing/main.go:442 +0x3f8

goroutine 33 [chan receive]:
github.com/syncthing/notify.(*nonrecursiveTree).dispatch(0xc00012c300, 0xc00012c240)
        github.com/syncthing/notify@v0.0.0-20201109091751-9a0e44181151/tree_nonrecursive.go:36 +0xb6
created by github.com/syncthing/notify.newNonrecursiveTree
        github.com/syncthing/notify@v0.0.0-20201109091751-9a0e44181151/tree_nonrecursive.go:29 +0xe5

goroutine 34 [chan receive]:
github.com/syncthing/notify.(*nonrecursiveTree).internal(0xc00012c300, 0xc00012c2a0)
        github.com/syncthing/notify@v0.0.0-20201109091751-9a0e44181151/tree_nonrecursive.go:81 +0x58
created by github.com/syncthing/notify.newNonrecursiveTree
        github.com/syncthing/notify@v0.0.0-20201109091751-9a0e44181151/tree_nonrecursive.go:30 +0x111

goroutine 35 [sleep]:
time.Sleep(0x1dcd6500)
        runtime/time.go:188 +0xbf
github.com/syncthing/syncthing/lib/dialer.init.1.func2()
        github.com/syncthing/syncthing/lib/dialer/internal.go:44 +0x2a
created by github.com/syncthing/syncthing/lib/dialer.init.1
        github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x15f

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        os/signal/signal.go:150 +0x45
root@abi-0:/# 
```

</p>
</details>

**Comment by JasonYangShadow** [comment]
goalng does not completely use glibc?

**Comment by munagekar** [comment]
Usually it does not use glibc. In my understanding you can get it to use glibc/musl by explicitly setting CGO_ENABLED=1, which is usually not done, to support cross-platform compilation.

**Comment by JasonYangShadow** [comment]
yes, if golang binaries are compiled with glibc and not statical linked. then LD_PRELOAD can work
